### ISSUE TITLE
Plugin.yml permissions

### ISSUE THREAD

**Issue by x1p** [MLG-Fortress/AutomaticInventory#10]
Could you add "permission: automaticinventory.sortchests" to the commands.autosort section of the plugin.yml?
This disables the tab completion of the command "/autosort"  if the player lacks this permission.

Paper 1.13.2

**Comment by x1p** [comment]
I hope I did it right. My first time doing this :)

**Comment by x1p** [comment]
Hehe I think I screwed it up :)

**Comment by x1p** [comment]
Tried to make a PR but it goes directly to the master. :-/
The change is very simple I just want to add:
`permission: automaticinventory.sortchests`
under `usage: /AutoSort`

**Comment by RoboMWM** [comment]
You could PR it if you wanna.

Otherwise I'll get to it sometime

**Comment by RoboMWM** [comment]
I think you're somehow using the wrong repo. Try clicking the edit button here: https://github.com/MLG-Fortress/AutomaticInventory/blob/master/resources/plugin.yml

**Comment by x1p** [comment]
Done. Hopefully it works. :-)
