### ISSUE TITLE
[Feature request] Config option to disable chest and inventory sorting by default

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#13]
It would be very cool to have an option in the config to disable sorting inventories and chest by default for all players.
Many players are confused at first. It would be better if everyone could knowingly activate the option by command and not have it enforced by default.

**Comment by RoboMWM** [comment]
Try https://ci.appveyor.com/project/RoboMWM39862/automaticinventory/builds/25299207/artifacts

**Comment by TheoRetisch1** [comment]
Thank you for your efforts! Unfortunately it does not load: https://pastebin.com/khDFD1zK

Paper 1.13.2 - 632

**Comment by RoboMWM** [comment]
Yea, I set api-version to 1.14 since this plugin has been updated for 1.14 APIs. I could look into backporting if this is necessary...
