### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#15]
Could you please add 1.14 support. Certainly not an easy and medium-term task. But it would be very cool to have an update as soon as the version is playable :)

Error: https://pastebin.com/zLryi41g
AutomaticInventory: 2.8.5
Paper 1.14.2 - 82

**Comment by RoboMWM** [comment]
I think this is a duplicate

**Comment by RoboMWM** [comment]
Duplicate of #14
