### ISSUE TITLE
Sorting into furnances and brewing stands - bug

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#16]
It is possible to use shift-left-click to place items in item slots where you can normally only place certain items. For example, the fuel slots of brewing stands and furnances can be filled with other materials. The players on my server would be very happy if AutomaticInventory would only sort in matching items!

Examples: https://imgur.com/a/ylFO83U
AutomaticInventory: 2.8.5
Paper 1.13.2 - 632

**Comment by RoboMWM** [comment]
Hmm, I guess when converting over to use the abstracted Container class these scenarios weren't thought about.

**Comment by RoboMWM** [comment]
and to confirm, does this also happen with `/depositall`?
