### ISSUE TITLE
Suggestion: Have barrels AutoSort and deposit.

### ISSUE THREAD

**Issue by Momshroom** [MLG-Fortress/AutomaticInventory#17]
Hi, 
I'm really enjoying this plugin and happy to see it's working on 1.14. Thanks for updating it!  I'd love it if barrels were included in the AutoSort and deposit functions.  
Thanks!

**Comment by RoboMWM** [comment]
I haven't played with the new 1.14(?) stuff, but ya probably should be easy to add support for them. I initially changed the plugin to support any container, which was an immediate issue as it started storing stuff in anvils, brewing stands, etc. lol.

**Comment by ghost** [comment]
With barrels: version 2.10.0 supports shift-clicking and /depositall, but it does not auto-sort itself.

**Comment by RoboMWM** [comment]
Can you make this a new issue?
