### ISSUE TITLE
depositall - NullPointerException

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#19]
If there are >= 8 blocks above a player >= 4 chests on top of each other, the following error occurs when sorting with depositall:
Thread-508/WARN]: Exception in thread "Thread-508" java.lang.NullPointerException
Screenshot: https://imgur.com/a/PPvar96

In all other constellations (lower height, fewer chests on top of each other) everything works fine.

AutomaticInventory 2.8.5
Paper 1.13.2 #648

**Comment by RoboMWM** [comment]
Need the full stacktrace

**Comment by RoboMWM** [comment]
Need the full stacktrace. If that's all that's printing, that means the full stacktrace was printed before, so either restart server and reproduce or look further back in logs

**Comment by TheoRetisch1** [comment]
Thank you for the reply! You're right, here is the full stacktrace:
https://pastebin.com/9E5gTPtD

**Comment by RoboMWM** [comment]
Uhh...... What's this? Sentry isn't in AutomaticInventory... Nor is this an error on the command...

**Comment by TheoRetisch1** [comment]
Well the first part of the error is caused for some reason by Easybackup. The second part by AutomaticInventory. However, EasyBackup is not the trigger, but only another consequence. With EasyBackup deactivated one get the same error, but only the last part of the error message: https://pastebin.com/BAWASaQv

**Comment by RoboMWM** [comment]
Uh... `getType` is annotated as `@NotNull` and thus shouldn't ever return null... 

Try reproducing without any other plugins installed?

**Comment by TheoRetisch1** [comment]
Yes, the same error occurs also without plugins and also with the newest AutomaticInventory version using Paper 1.14.4.

**Comment by RoboMWM** [comment]
This is odd. Will prepare a debug version for you to test with further to get more info. Sounds like a potential craftbukkit/spigot/paper bug.

**Comment by RoboMWM** [comment]
Same error? Can you please paste the new stacktrace?

**Comment by TheoRetisch1** [comment]
The only difference is the thread number: https://pastebin.com/AHpdXKnB
(latest version, paper 1.14.4, no plugins enabled)

**Comment by RoboMWM** [comment]
Line number is different to, which is what I was looking for. Thanks.

Will prepare a debug version

**Comment by RoboMWM** [comment]
So ya that new stacktrace was helpful. Turns out the FindChestsThread will return null for Material if it searches out of bounds, but this null is never checked. There was no need to check before because Big_Scary's original code only checked if it was equal to a specific material, instead of calling a method on it.

**Comment by TheoRetisch1** [comment]
Thank you it works perfectly fine!
