### ISSUE TITLE
Vanilla-Accessible chests are reported as blocked

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#2]
If you place several boxes on top of each other or slaps over a box so that you can still open it, shift-left-click does not always work. The text message "ChestLidBlocked" is triggered and the items are not sorted. There is no error in the console. It would be very cool if you could have a look at the accessibility check of the boxes.

AutomaticInventory 2.8.4
Paper 1.13.2 - 597

**Comment by RoboMWM** [comment]
There's a PR pending for this, please see #1 and give input if you know how Minecraft determines a chest is openable.

**Comment by RoboMWM** [comment]
To centralize discussion, please move conversation to #1

**Comment by RoboMWM** [comment]
Closed in #1
