### ISSUE TITLE
[Bug] Auto-Refill does not detect when plugin sets item durability to 0

### ISSUE THREAD

**Issue by MattAKAFred** [MLG-Fortress/AutomaticInventory#29]
Auto-refilling tools does not work when plugins manually adjust item durability - for example, when an axe breaks while harvesting a tree with [Ultimate Timber](https://songoda.com/marketplace/product/ultimatetimber-the-realistic-tree-chopper.18) the axe is not replaced from inventory.

**Comment by RoboMWM** [comment]
I'd suggest using plugins like GraviTree (https://dev.bukkit.org/projects/gravitree) which work alongside vanilla mechanics. That being said, if the plugin is modifying the durability, then the plugin should fire the respective events appropriately (in this case, ItemDamageEvent iirc). Else, there's no way for any other plugin to know what happened to the item.
