### ISSUE TITLE
NPE on PotionType#getEffectType

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#3]
Sometimes the following error message appears in the log during sorting with /depositall. According to the current status, however, this has no negative effects. Unfortunatly I was not able to reproduce it step by step. Do you recognize the cause by the error?

error: https://pastebin.com/4PNe6LfW
AutomaticInventory 2.8.4
Paper 1.13.2 - 597

```
[21:46:40] [Server thread/INFO]: BarSerkr issued server command: /depositall
[21:46:44] [Server thread/WARN]: [AutomaticInventory] Task #2033577 for AutomaticInventory v2.8.4 generated an exception
java.lang.NullPointerException: null
	at me.ryanhamshire.AutomaticInventory.AutomaticInventory.getSignature(AutomaticInventory.java:404) ~[?:?]
	at me.ryanhamshire.AutomaticInventory.AutomaticInventory.depositMatching(AutomaticInventory.java:346) ~[?:?]
	at me.ryanhamshire.AutomaticInventory.FindChestsThread$QuickDepositChain.run(FindChestsThread.java:215) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1009) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-597]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```

**Comment by RoboMWM** [comment]
Has to do with potions. I guess it was a blank potion (e.g. water bottle)?

https://github.com/MLG-Fortress/AutomaticInventory/blob/dcfa6893aad328b950507aadffcfec322e73ae1f/src/me/ryanhamshire/AutomaticInventory/AutomaticInventory.java#L402-L407

**Comment by TheoRetisch1** [comment]
You're right! It is actually empty bottles and full water bottles that are not sorted.  In addition, the following error appears in the log: https://pastebin.com/RhWNtB3N

**Comment by RoboMWM** [comment]
Exact same error. Just stacktrace is truncated since it was printed a bunch of times before.

**Comment by RoboMWM** [comment]
Ok, so there are [Potion Types](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionType.html#getByEffect-org.bukkit.potion.PotionEffectType-) and [PotionEffect Types](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html). The difference seems to be that PotionEffectType refers to all of the potion effects that can be applied to an entity via `/effect` or via potion, whereas PotionType refers only to the base potions (i.e. the ones that can be obtained via creative inventory), and includes things like "Water."

I'm actually not too familiar with potions, I remember them coming out with 1.0 which is about the time I took a break from Minecraft so I never got into enchanting and experience - so I'm not aware of the intricacies of potions.

With that in mind, what makes sense to me is to just use the PotionType as part of the item signature instead of trying to obtain the PotionEffectType. That way water bottles and empty bottles will be sorted, and potions will be sorted on their type rather than the effect they provide (in most cases, it seems the type and effect are linked but looking at those two enums, there are more PotionEffectTypes so I'm sure there are some specific differences). How does that sound?

**Comment by TheoRetisch1** [comment]
According to the explanation at the following link, it is very likely that your idea will work: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/package-summary.html

**Comment by Momshroom** [comment]
I think this is related:
When do /da with a potion in inventory, items are not deposited and the following error occurs:
https://pastebin.com/4h7rZ3ce


When doing /da with a chest nearby with potions in the chest (but none in inventory):
https://pastebin.com/sUUGPTnb

If the chest is not the closest chest, chests will be checked and deposits made until the potion containing chest is found and then the process will break with the NPE


Shift punching quick deposit works when the chest has a potion

But NOT when the chest has a water bottle:
https://pastebin.com/1z5LcmxZ
1.13.2March13th.jar:git-Spigot-3cb9dcb-8d8475f] 04.04 18:50:16 [Server] INFO ... 17 more


Running Spigot 1.13.2
AutomaticInventory 2.8.4 - I did open the plugin.yml and make permissions default to off but no other changes, default config.

**Comment by RoboMWM** [comment]
Did you copy from a server panel console? Because there's no newlines in any of those pastes... please copy from latest.log next time.

**Comment by Momshroom** [comment]
I did, sorry.  I can recopy them if you'd like.  They just seemed short enough to be readable this way this time and it's a lot easier.

**Comment by RoboMWM** [comment]
I'm assuming they're the same.

No stacktrace is readable without newlines.

**Comment by Momshroom** [comment]
The error from my logs when  doing /da with a potion in inventory, items are not deposited:
https://pastebin.com/C67GQAHa

The error when doing /da with a chest nearby with potions in the chest (but none in inventory) appears to be the same as above.

But NOT when shift click punching a chest that has a water bottle: appears to be a different error:
https://pastebin.com/E2HcnymC

Sorry for the prior error formatting issues.

**Comment by RoboMWM** [comment]
Btw, instead of using pastebin you can paste in here directly using three backticks

    ```
    like this
    ```

**Comment by RoboMWM** [comment]
And the errors are the same, in that the same line is the cause of the exception.

```
java.lang.NullPointerException: null
	at me.ryanhamshire.AutomaticInventory.AutomaticInventory.getSignature(AutomaticInventory.java:404)
```

**Comment by RoboMWM** [comment]
Try this and let me know if it works https://ci.appveyor.com/project/RoboMWM39862/automaticinventory/builds/23654330/artifacts

**Comment by TheoRetisch1** [comment]
It works! Thanks :)
