### ISSUE TITLE
Sorting / DepositAll do not work with barrels

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/AutomaticInventory#40]
When using **barrels** in out storage room the following features do not work:
- Auto sorting of the barrel's inventory
- /DepositAll

But these work for **chests** in the same room.
Also tried to use the plugin with a barrel in the middle of nowhere in case something in the room specifically was causing the bug, and ran into the same issues.

However, the following _still works with barrels_:
- Left Shift + Left Click to specifically target one barrel and deposit matching items in it

**Comment by RoboMWM** [comment]
What `/version AutomaticInventory` are you running, apparently this has been addressed over a year ago. https://github.com/MLG-Fortress/AutomaticInventory/issues/20

And in that case it did seem to be supporting /depositall so not sure what changed.

**Comment by ghost** [comment]
I'm running **2.12.2** of the plugin which should be the latest (grabbed from https://dev.bukkit.org/projects/automatic-inventory/files) That's also the only plugin on our server.

The server is running "CraftBukkit version 2992-Spigot-018b9a0-b5eb2f5 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)" and it tells me I am 3 versions behind when I use /version on the server. I'm assuming this wouldn't cause issues but maybe I'm wrong?

**Comment by RoboMWM** [comment]
Weird. Guess I'll check what barrels are...

**Comment by RoboMWM** [comment]
Yea, barrels are included everywhere in the code. You tested with the same scenarios for a chest? Because I think the block's inventory needs to have some of the same items in order to be deposited into it.

**Comment by RoboMWM** [comment]
Ok, I may have found the reason for not autosorting but ~~idk if this is used for /depositall~~ Ok it is.

**Comment by ghost** [comment]
> Yea, barrels are included everywhere in the code. You tested with the same scenarios for a chest? Because I think the block's inventory needs to have some of the same items in order to be deposited into it.

I know you closed it already and appear to have found the reasons behind it (awesome), for the sake of clarity I just wanted to say that I did test with 32 dirt already present in the barrel and 32 on me. This scenario worked with chests in the same room.
Thanks for looking into this by the way!
