### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [MLG-Fortress/AutomaticInventory#44]
Using 1.16.5 airplane paper fork
https://nekobin.com/fapimebezu

**Comment by RoboMWM** [comment]
Did this paste expire or something? Try using gist or mclo.gs

**Comment by LucidAPs** [comment]
Yeah I don't know what happened there. Here it is https://mclo.gs/7RYUXLh

**Comment by RoboMWM** [comment]
duplicate of #41 

I was going to push an update via BukkitDev's API but I still haven't gotten around to doing that I guess. Ugh.

**Comment by LucidAPs** [comment]
Are you going to push an update for the plugin?
