### ISSUE TITLE
Only use auto-refill feature

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MLG-Fortress/AutomaticInventory#5]
It would be cool, if one could disable e.g. inventory sorting completely (I only need the auto refill for the hotbar)

**Comment by TheoRetisch1** [comment]
I think these two commanders are doing exactly what you want? You can find them in the plugin description or what exactly do you have in mind?

`/AutoSort chests` toggles automatic chest sorting on or off.

`/AutoSort inventory` toggles automatic personal inventory sorting on or off.

**Comment by RoboMWM** [comment]
Please see TheoRetisch1's comment - if that command isn't sufficient (my guess is that it probably would disable autorefill?), try seeing if setting permissions will work. Can't recall them offhand but they're on the project page.

**Comment by RoboMWM** [comment]
Yea, looks like you can negate all permissions except for `automaticinventory.refillstacks` and you'll have exactly what you want.

**Comment by ThexXTURBOXx** [comment]
Okay, didn't think about the permissions. Thank you!
