### ISSUE TITLE
Depositall doesn't work below height y -13

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#50]
If you execute `depositall` for chests below height y -13, an internal error occurs and the items are not sorted. In chests above y -13 all items are sorted without problems.

AutomaticInventory - 2.12.3-5e759dd
Paper 1.19.2 - 141

**Comment by TheoRetisch1** [comment]
Do you see a possibility to fix the problem?

**Comment by Momshroom** [comment]
I'm having the same issue:  
Here's the console error: 
https://pastebin.com/qpwU4eyW

Additional note:  a chest at y=-5 and y = -13  fails to receive deposits, but does not cause the console errors.   Chests at y=-17 cause the error and also do not deposit.  chests higher up work fine.  I have not pinpointed the exact locations where it errors.

**Comment by Momshroom** [comment]
Forgot to say, running:
Paper version git-Paper-265 (MC: 1.19.2)
AutomaticInventory version 2.12.2-3a60582

**Comment by Momshroom** [comment]
line 243 of the AutomaticInventory.java file:
`int minY = Math.max(0, player.getEyeLocation().getBlockY() - 10); `
is likely a large part of the problem:  
should be:
`int minY = Math.max(world.getMinHeight(), player.getEyeLocation().getBlockY() - 10);`

I can try testing this and PRing a fix, but probably not before Dec 9th.

**Comment by Momshroom** [comment]
Line 45 in FindChestsThread.java will still need adjusting for the fact that negative y coords can still lead to a negative value there in the array declaration.

**Comment by TheoRetisch1** [comment]
I would love to see a pull request @Momshroom 👍
