### ISSUE TITLE
Feeding animals

### ISSUE THREAD

**Issue by x1p** [MLG-Fortress/AutomaticInventory#9]
Auto Refills does not seem to recognize the feeding of animals.

Steps to reproduce:
1. Take 2 stacks wheat
2. Feed animals
3. stack is not refilled from inventory

Paper 1.13.2

**Comment by RoboMWM** [comment]
Interact prolly isn't checked. Idk how expensive it'd be to check, I guess could add as config option.

**Comment by RoboMWM** [comment]
Yea, interact is only checked for chests or something.

**Comment by x1p** [comment]
Understood. It was more a observation that feeding didn't auto refill. I leave it up to you to decide what the future will bring. Sure it's a nice enchantment as long as it doesn't impact a server to much or everyone can decide for themselves.

**Comment by RoboMWM** [comment]
Yup, interact isn't checked. There are currently 5 event handlers that trigger the refill check:
- PlayerItemBreakEvent (tools breaking)
- Blockplaceevent
- BlockFertilizeEvent
- PlayerItemConsumeEvent
- ProjectileLaunchEvent

I'll add PlayerInteractEntityEvent

**Comment by x1p** [comment]
Ok, thanks. I see quite a few events already. 
In order to save performance, is it wise to have an option to disable certain events?

**Comment by RoboMWM** [comment]
If performance is an issue you'll see it in timings.

> Premature optimization is the root of all evil

  \- some PM, probably
